import type { Course } from "@/types/lesson";

/**
 * Panda course metadata.
 *
 * This is the navigational skeleton only — module and lesson titles,
 * ordering, difficulty and prerequisites. Actual lesson content lives in
 * each lesson's `blocks` and is authored separately.
 */

const modules: Course["modules"] = [
  {
    id: "introduction",
    title: "Introduction",
    description: "First steps",
    order: 1,
    icon: "sparkles",
    lessons: ["what-is-git", "why-git", "version-control"],
  },
  {
    id: "git-basics",
    title: "Git Basics",
    description: "Core building blocks",
    order: 2,
    icon: "layers",
    lessons: [
      "repository",
      "commit",
      "branch",
      "checkout",
      "merge",
      "rebase",
    ],
  },
  {
    id: "github",
    title: "GitHub",
    description: "Share and collaborate",
    order: 3,
    icon: "globe",
    lessons: ["remote", "push", "pull", "clone", "fork", "pull-request"],
  },
  {
    id: "advanced",
    title: "Advanced",
    description: "Go deeper",
    order: 4,
    icon: "rocket",
    lessons: ["advanced-git", "ci-cd"],
  },
];

const lessons: Course["lessons"] = {
  "what-is-git": {
    meta: {
      id: "what-is-git",
      slug: "what-is-git",
      title: "What is Git?",
      description: "The time machine for your code.",
      module: "introduction",
      order: 1,
      durationMinutes: 8,
      difficulty: "beginner",
      tags: ["basics"],
    },
    blocks: [],
  },
  "why-git": {
    meta: {
      id: "why-git",
      slug: "why-git",
      title: "Why Git?",
      description: "The problem Git solves.",
      module: "introduction",
      order: 2,
      durationMinutes: 7,
      difficulty: "beginner",
      tags: ["basics"],
    },
    blocks: [],
  },
  "version-control": {
    meta: {
      id: "version-control",
      slug: "version-control",
      title: "Version Control",
      description: "Track every change.",
      module: "introduction",
      order: 3,
      durationMinutes: 10,
      difficulty: "beginner",
      tags: ["basics"],
    },
    blocks: [],
  },
  repository: {
    meta: {
      id: "repository",
      slug: "repository",
      title: "Repository",
      description: "Your project's home.",
      module: "git-basics",
      order: 1,
      durationMinutes: 12,
      difficulty: "beginner",
      prerequisites: ["what-is-git"],
      tags: ["basics"],
    },
    blocks: [],
  },
  commit: {
    meta: {
      id: "commit",
      slug: "commit",
      title: "Commit",
      description: "Save a moment in time.",
      module: "git-basics",
      order: 2,
      durationMinutes: 15,
      difficulty: "beginner",
      prerequisites: ["repository"],
      tags: ["basics"],
    },
    blocks: [],
  },
  branch: {
    meta: {
      id: "branch",
      slug: "branch",
      title: "Branch",
      description: "Work in parallel worlds.",
      module: "git-basics",
      order: 3,
      durationMinutes: 15,
      difficulty: "beginner",
      prerequisites: ["commit"],
      tags: ["branches"],
    },
    blocks: [],
  },
  checkout: {
    meta: {
      id: "checkout",
      slug: "checkout",
      title: "Checkout",
      description: "Move between branches.",
      module: "git-basics",
      order: 4,
      durationMinutes: 10,
      difficulty: "beginner",
      prerequisites: ["branch"],
      tags: ["branches"],
    },
    blocks: [],
  },
  merge: {
    meta: {
      id: "merge",
      slug: "merge",
      title: "Merge",
      description: "Combine branches together.",
      module: "git-basics",
      order: 5,
      durationMinutes: 15,
      difficulty: "intermediate",
      prerequisites: ["checkout"],
      tags: ["branches"],
    },
    blocks: [],
  },
  rebase: {
    meta: {
      id: "rebase",
      slug: "rebase",
      title: "Rebase",
      description: "Replay commits on top.",
      module: "git-basics",
      order: 6,
      durationMinutes: 18,
      difficulty: "intermediate",
      prerequisites: ["merge"],
      tags: ["branches"],
    },
    blocks: [],
  },
  remote: {
    meta: {
      id: "remote",
      slug: "remote",
      title: "Remote",
      description: "Connect to a faraway repo.",
      module: "github",
      order: 1,
      durationMinutes: 10,
      difficulty: "intermediate",
      prerequisites: ["rebase"],
      tags: ["remote"],
    },
    blocks: [],
  },
  push: {
    meta: {
      id: "push",
      slug: "push",
      title: "Push",
      description: "Send commits to the remote.",
      module: "github",
      order: 2,
      durationMinutes: 10,
      difficulty: "intermediate",
      prerequisites: ["remote"],
      tags: ["remote"],
    },
    blocks: [],
  },
  pull: {
    meta: {
      id: "pull",
      slug: "pull",
      title: "Pull",
      description: "Bring commits down.",
      module: "github",
      order: 3,
      durationMinutes: 10,
      difficulty: "intermediate",
      prerequisites: ["remote"],
      tags: ["remote"],
    },
    blocks: [],
  },
  clone: {
    meta: {
      id: "clone",
      slug: "clone",
      title: "Clone",
      description: "Copy a repository locally.",
      module: "github",
      order: 4,
      durationMinutes: 9,
      difficulty: "intermediate",
      prerequisites: ["remote"],
      tags: ["remote"],
    },
    blocks: [],
  },
  fork: {
    meta: {
      id: "fork",
      slug: "fork",
      title: "Fork",
      description: "Your own copy of a repo.",
      module: "github",
      order: 5,
      durationMinutes: 8,
      difficulty: "intermediate",
      prerequisites: ["clone"],
      tags: ["github"],
    },
    blocks: [],
  },
  "pull-request": {
    meta: {
      id: "pull-request",
      slug: "pull-request",
      title: "Pull Request",
      description: "Propose a change to a project.",
      module: "github",
      order: 6,
      durationMinutes: 15,
      difficulty: "intermediate",
      prerequisites: ["fork"],
      tags: ["github"],
    },
    blocks: [],
  },
  "advanced-git": {
    meta: {
      id: "advanced-git",
      slug: "advanced-git",
      title: "Advanced Git",
      description: "Power tools under the hood.",
      module: "advanced",
      order: 1,
      durationMinutes: 25,
      difficulty: "advanced",
      prerequisites: ["pull-request"],
      tags: ["advanced"],
    },
    blocks: [],
  },
  "ci-cd": {
    meta: {
      id: "ci-cd",
      slug: "ci-cd",
      title: "CI/CD",
      description: "Automate your workflow.",
      module: "advanced",
      order: 2,
      durationMinutes: 20,
      difficulty: "advanced",
      prerequisites: ["advanced-git"],
      tags: ["advanced"],
    },
    blocks: [],
  },
};

export const course: Course = {
  name: "Panda",
  modules,
  lessons,
};